import type { Question } from "./types";

/* Sign-recognition questions: each shows a road sign (rendered by SignGlyph from
 * its signId) and asks what it means. Category is road-and-traffic-signs. */
export const SIGN_QUESTIONS: Question[] = [
  { id: "sign-q-001", category: "road-and-traffic-signs", signId: "reg-stop", question: "What does this sign mean?", options: ["Stop and give way", "Give way to traffic on the major road", "No entry", "End of restriction"], correct: [0], selectCount: 1, explanation: "The octagonal STOP sign means you must stop completely at the line and give way, whatever the traffic conditions." },
  { id: "sign-q-002", category: "road-and-traffic-signs", signId: "reg-give-way", question: "What does this sign mean?", options: ["Stop", "Give way to traffic on the major road", "No vehicles", "Roundabout ahead"], correct: [1], selectCount: 1, explanation: "The inverted triangle means give way to traffic on the major road; stop if necessary." },
  { id: "sign-q-003", category: "road-and-traffic-signs", signId: "reg-no-entry", question: "What does this sign mean?", options: ["No stopping", "No through road", "No entry for vehicular traffic", "One-way street"], correct: [2], selectCount: 1, explanation: "A red disc with a white horizontal bar means no entry for vehicular traffic." },
  { id: "sign-q-004", category: "road-and-traffic-signs", signId: "warn-roundabout", question: "What does this sign warn of?", options: ["A mini-roundabout you must use", "A roundabout ahead", "A ring road", "No right turn"], correct: [1], selectCount: 1, explanation: "A red triangle warns of a hazard — here, a roundabout ahead. Be ready to give way to traffic from the right." },
  { id: "sign-q-005", category: "road-and-traffic-signs", signId: "warn-children", question: "What does this warning sign mean?", options: ["Playground — no vehicles", "Children or a school crossing ahead", "Pedestrian zone", "Cycle route"], correct: [1], selectCount: 1, explanation: "This warns of children, e.g. near a school. Be ready to slow down or stop." },
  { id: "sign-q-006", category: "road-and-traffic-signs", signId: "warn-slippery", question: "What does this warning sign mean?", options: ["Slippery road ahead", "Road liable to flooding", "Loose chippings", "Ford ahead"], correct: [0], selectCount: 1, explanation: "The skidding-car symbol warns the road may be slippery — reduce speed and avoid harsh braking." },
  { id: "sign-q-007", category: "road-and-traffic-signs", signId: "warn-road-narrows", question: "What does this warning sign mean?", options: ["Road narrows on both sides", "Two-way traffic", "Dual carriageway ends", "Width limit ahead"], correct: [0], selectCount: 1, explanation: "It warns that the road narrows on both sides ahead." },
  { id: "sign-q-008", category: "road-and-traffic-signs", signId: "reg-30", question: "What does this sign mean?", options: ["Recommended speed 30 mph", "Maximum speed 30 mph", "Minimum speed 30 mph", "End of 30 mph zone"], correct: [1], selectCount: 1, explanation: "A number in a red ring is a mandatory maximum speed limit — here 30 mph." },
  { id: "sign-q-009", category: "road-and-traffic-signs", signId: "reg-national", question: "What does this sign mean?", options: ["No speed limit applies", "National speed limit applies", "End of motorway", "Derestricted for HGVs only"], correct: [1], selectCount: 1, explanation: "The white circle with a black diagonal means the national speed limit applies (e.g. 60 single / 70 dual carriageway for cars)." },
  { id: "sign-q-010", category: "road-and-traffic-signs", signId: "reg-no-overtaking", question: "What does this sign mean?", options: ["No overtaking", "Two-way traffic", "Priority over oncoming vehicles", "No motor vehicles"], correct: [0], selectCount: 1, explanation: "The two cars in a red ring mean no overtaking until the end-of-restriction sign." },
  { id: "sign-q-011", category: "road-and-traffic-signs", signId: "mand-ahead-only", question: "What does this blue sign mean?", options: ["Ahead only", "One-way traffic", "Minimum speed", "No left or right turn"], correct: [0], selectCount: 1, explanation: "A blue circle gives a positive instruction. The upward arrow means ahead only." },
  { id: "sign-q-012", category: "road-and-traffic-signs", signId: "mand-keep-left", question: "What does this sign mean?", options: ["Turn left ahead", "Keep left", "No right turn", "One-way to the left"], correct: [1], selectCount: 1, explanation: "A blue circle with the arrow means keep left — pass to the left of the sign or island." },
  { id: "sign-q-013", category: "road-and-traffic-signs", signId: "mand-mini-roundabout", question: "What does this sign mean?", options: ["Roundabout ahead — warning", "Mini-roundabout: give way to traffic from the right", "No U-turns", "Turn right only"], correct: [1], selectCount: 1, explanation: "The blue circular-arrows sign marks a mini-roundabout. Give way to traffic from your right." },
  { id: "sign-q-014", category: "road-and-traffic-signs", signId: "warn-level-crossing", question: "What does this warning sign mean?", options: ["Tramway crossing", "Level crossing without a barrier or gate ahead", "Low bridge", "Quayside or river bank"], correct: [1], selectCount: 1, explanation: "This warns of a level crossing without a barrier or gate ahead." },
  { id: "sign-q-015", category: "road-and-traffic-signs", signId: "info-parking", question: "What does this sign indicate?", options: ["Parking place", "No waiting", "Park and ride", "Lay-by ahead"], correct: [0], selectCount: 1, explanation: "A blue rectangle with a white 'P' indicates a parking place." },
  { id: "sign-q-016", category: "road-and-traffic-signs", signId: "warn-tjunction", question: "What does this warning sign mean?", options: ["Crossroads ahead", "T-junction ahead", "Side road on the right", "No through road"], correct: [1], selectCount: 1, explanation: "It warns of a T-junction ahead — the road you're on ends; give way to traffic on the major road." },
  { id: "sign-q-017", category: "road-and-traffic-signs", signId: "warn-roadworks", question: "What does this warning sign mean?", options: ["Men working overhead", "Roadworks ahead", "Loose chippings", "Construction site entrance"], correct: [1], selectCount: 1, explanation: "The worker symbol in a red triangle warns of roadworks ahead — slow down and watch for changes in layout." },
  { id: "sign-q-018", category: "road-and-traffic-signs", signId: "reg-no-waiting", question: "What does this sign mean?", options: ["No stopping (clearway)", "No waiting", "No parking on the verge", "Limited waiting"], correct: [1], selectCount: 1, explanation: "A blue circle with a red ring and one red diagonal means no waiting." },
];
